version: '3.3'


services:
  auth-service:
    build:
      context: ./auth
      dockerfile: build/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080

  user-service:
    build:
      context: ./user
      dockerfile: build/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - PORT=8081

  friendship-service:
    build:
      context: ./friendship
      dockerfile: build/Dockerfile
    ports:
      - "8082:8082"
    environment:
      - PORT=8082

  chat-service:
    build:
      context: ./chat
      dockerfile: build/Dockerfile
    ports:
      - "8083:8083"
    environment:
      - PORT=8083

  notification-service:
    build:
      context: ./notification
      dockerfile: build/Dockerfile
    ports:
      - "8084:8084"
    environment:
      - PORT=8084