version: '3.3'

services:
  auth-service:
    build:
      context: ./auth
    ports:
      - "8080:8080"
    environment:
      - PORT=8080

  user-service:
    build:
      context: ./user
    ports:
      - "8081:8081"
    environment:
      - PORT=8081

  friendship-service:
    build:
      context: ./friendship
    ports:
      - "8082:8082"
    environment:
      - PORT=8082

  chat-service:
    build:
      context: ./chat
    ports:
      - "8083:8083"
    environment:
      - PORT=8083

  notification-service:
    build:
      context: ./notification
    ports:
      - "8084:8084"
    environment:
      - PORT=8084
