version: '3.3'

networks:
  app-network:
    driver: bridge


services:
  auth-service:
    build:
      context: ./auth
      dockerfile: build/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - AUTH_PORT=8080
    networks:
      - app-network

  user-service:
    build:
      context: ./user
      dockerfile: build/Dockerfile
    ports:
      - "8081:8080"
    environment:
      - USER_PORT=8081
    networks:
      - app-network

  friendship-service:
    build:
      context: ./friendship
      dockerfile: build/Dockerfile
    ports:
      - "8082:8080"
    environment:
      - FRIENDSHIP_PORT=8082
    networks:
      - app-network

  chat-service:
    build:
      context: ./chat
      dockerfile: build/Dockerfile
    ports:
      - "8083:8080"
    environment:
      - CHAT_PORT=8083
    networks:
      - app-network

  notification-service:
    build:
      context: ./notification
      dockerfile: build/Dockerfile
    ports:
      - "8084:8080"
    environment:
      - NOTIFICATION_PORT=8084
    networks:
      - app-network